# =================================================================
# Default Listener
# =================================================================

# Listen on port 1883 on all network interfaces (0.0.0.0)
# This allows the 'publisher' container to connect to 'mqtt-broker'
listener 1883 0.0.0.0

# Allow anonymous connections (No username/password required)
# Essential for initial testing and development
allow_anonymous true

# =================================================================
# Logging
# =================================================================

# Send logs to the standard output so you can see them via 'docker logs'
log_dest stdout
log_type all
log_type warning
log_type notice
log_type information
log_type debug

# =================================================================
# Persistence
# =================================================================

# Save the internal database to the data folder
persistence true
persistence_location /mosquitto/data/

message_size_limit 0