[[publishers]]
name = "PLC0"
publisherId = 10000

[[publishers.writerGroups]]
id = 100
interval = 1000
name = "Processors / CPU"

[[publishers.writerGroups.dataSets]]
writerId = 105
name = "core_105"
fields = [
    { name = "coreThermalHeadroom", type = "Float" },
]


[[publishers.writerGroups.dataSets]]
writerId = 205
name = "core_205"
fields = [
    { name = "20coreThermalHeadroom", type = "Float" },
]

