[[publishers]]
name = "PLC0"
publisherId = 41
[[publishers.writerGroups]]
id = 22
interval = 500
name = "Group"
[[publishers.writerGroups.dataSets]]
writerId = 0
name = "writer_0"
fields = [
  { name = "0_0", type = "Real" },
  { name = "0_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 1
name = "writer_1"
fields = [
  { name = "1_0", type = "Real" },
  { name = "1_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 2
name = "writer_2"
fields = [
  { name = "2_0", type = "Real" },
  { name = "2_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 3
name = "writer_3"
fields = [
  { name = "3_0", type = "Real" },
  { name = "3_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 4
name = "writer_4"
fields = [
  { name = "4_0", type = "Real" },
  { name = "4_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 5
name = "writer_5"
fields = [
  { name = "5_0", type = "Real" },
  { name = "5_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 6
name = "writer_6"
fields = [
  { name = "6_0", type = "Real" },
  { name = "6_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 7
name = "writer_7"
fields = [
  { name = "7_0", type = "Real" },
  { name = "7_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 8
name = "writer_8"
fields = [
  { name = "8_0", type = "Real" },
  { name = "8_1", type = "Real" },
]

[[publishers.writerGroups.dataSets]]
writerId = 9
name = "writer_9"
fields = [
  { name = "9_0", type = "Real" },
  { name = "9_1", type = "Real" },
]
